In [1]:
! pip install setfit datasets scikit-learn pandas "transformers<5.0"

Requirement already satisfied: setfit in /usr/local/lib/python3.12/dist-packages (1.1.3)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: transformers<5.0 in /usr/local/lib/python3.12/dist-packages (4.57.6)
Requirement already satisfied: sentence-transformers>=3 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers[train]>=3->setfit) (5.4.0)
Requirement already satisfied: evaluate>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from setfit) (0.4.6)
Requirement already satisfied: huggingface_hub>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from setfit) (0.36.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from setfit) (26.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.25.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0) (0.7.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.13.5)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.24.0->setfit) (1.4.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.24.0->setfit) (4.15.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2026.2.25)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=3->sentence-transformers[train]>=3->setfit) (2.10.0+cu128)
Requirement already satisfied: accelerate>=0.20.3 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers[train]>=3->setfit) (1.13.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate>=0.20.3->sentence-transformers[train]>=3->setfit) (5.9.5)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=3->sentence-transformers[train]>=3->setfit) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=3->sentence-transformers[train]>=3->setfit) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=3->sentence-transformers[train]>=3->setfit) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=3->sentence-transformers[train]>=3->setfit) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=3->sentence-transformers[train]>=3->setfit) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=3->sentence-transformers[train]>=3->setfit) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=3->sentence-transformers[train]>=3->setfit) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=3->sentence-transformers[train]>=3->setfit) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=3->sentence-transformers[train]>=3->setfit) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=3->sentence-transformers[train]>=3->setfit) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=3->sentence-transformers[train]>=3->setfit) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=3->sentence-transformers[train]>=3->setfit) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=3->sentence-transformers[train]>=3->setfit) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=3->sentence-transformers[train]>=3->setfit) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=3->sentence-transformers[train]>=3->setfit) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=3->sentence-transformers[train]>=3->setfit) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=3->sentence-transformers[train]>=3->setfit) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=3->sentence-transformers[train]>=3->setfit) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=3->sentence-transformers[train]>=3->setfit) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=3->sentence-transformers[train]>=3->setfit) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=3->sentence-transformers[train]>=3->setfit) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.11.0->sentence-transformers>=3->sentence-transformers[train]>=3->setfit) (1.5.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers>=3->sentence-transformers[train]>=3->setfit) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers>=3->sentence-transformers[train]>=3->setfit) (3.0.3)

In [2]:
import setfit
import pickle

import pandas as pd
from datasets import Dataset
from setfit import SetFitModel, Trainer, TrainingArguments
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

ImportError: cannot import name 'default_logdir' from 'transformers.training_args' (/usr/local/lib/python3.12/dist-packages/transformers/training_args.py)

In [ ]:
import pickle

import pandas as pd
from datasets import Dataset
from setfit import SetFitModel, Trainer, TrainingArguments
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

with open("clustered_by_label.pkl", "rb") as f:
    clustered_by_label = pickle.load(f)

rows = []
for label, payload in clustered_by_label.items():
    for text in payload.get("representative_texts", []):
        rows.append({"text": str(text), "label_raw": str(label)})

rep_df = pd.DataFrame(rows).drop_duplicates(subset=["text"]).reset_index(drop=True)
print({"representative_rows": len(rep_df), "raw_labels": rep_df["label_raw"].value_counts().to_dict()})
rep_df.head()

{'representative_rows': 100, 'raw_labels': {'casual': 20, 'possibly_needs_caution': 20, 'probably_needs_caution': 20, 'needs_caution': 20, 'needs_intervention': 20}}

                                                text label_raw
0      Yeah, but I feel bad about how terrible I am.    casual
1                She has always treated me unfairly.    casual
2  I need to tell them not to come next time, I t...    casual
3  I don't always put kitchen utensils in the exa...    casual
4  He could still come back to a relationship wit...    casual

In [ ]:
rep_df["label_3"] = rep_df["label_raw"].replace(
    {
        "casual": "safe",
        "possibly_needs_caution": "possibly_needs_caution",
        "probably_needs_caution": "probably_needs_caution",
        "needs_caution": "needs_caution",
        "needs_intervention": "needs_intervention",
    }
)

label_encoder = LabelEncoder()
rep_df["label_enc"] = label_encoder.fit_transform(rep_df["label_3"])

train_df_setfit, valid_df_setfit = train_test_split(
    rep_df,
    test_size=0.30,
    random_state=42,
    stratify=rep_df["label_enc"],
)

print({"train_rows": len(train_df_setfit), "valid_rows": len(valid_df_setfit), "classes": label_encoder.classes_.tolist()})
valid_df_setfit.head(2)

{'train_rows': 70, 'valid_rows': 30, 'classes': ['needs_caution', 'needs_intervention', 'possibly_needs_caution', 'probably_needs_caution', 'safe']}

,text,label_raw,label_3,label_enc
23,I'm going to end up married to her.,possibly_needs_caution,possibly_needs_caution,2
39,"I like looking at pretty things, when it comes...",possibly_needs_caution,possibly_needs_caution,2

In [ ]:
train_dataset = Dataset.from_pandas(
    train_df_setfit[["text", "label_enc"]].rename(columns={"label_enc": "label"}),
    preserve_index=False,
)

model_id = "sentence-transformers/all-MiniLM-L6-v2"
model = SetFitModel.from_pretrained(model_id, labels=[0, 1, 2])

args = TrainingArguments(
    batch_size=16,
    num_epochs=3,
    evaluation_strategy="no",
    save_strategy="no",
)

trainer = Trainer(
    model=model,
    args=args,
    train_dataset=train_dataset,
)

trainer.train()
print({"model": model_id, "epochs": 3})

model_head.pkl not found on HuggingFace Hub, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.
The `evaluation_strategy` argument is deprecated and will be removed in a future version. Please use `eval_strategy` instead.

Map:   0%|          | 0/70 [00:00<?, ? examples/s]

***** Running training *****
  Num unique pairs = 3920
  Batch size = 16
  Num epochs = 3
d:\DevTools\Python313\Lib\site-packages\torch\utils\data\dataloader.py:668: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

{'model': 'sentence-transformers/all-MiniLM-L6-v2', 'epochs': 3}

In [ ]:
test = valid_df_setfit.copy()
texts = test["text"].tolist()

pred_enc = [int(pred) for pred in model.predict(texts, use_labels=False)]
probas = model.predict_proba(texts)
pred_labels = label_encoder.inverse_transform(pred_enc)

out = pd.DataFrame(
    {
        "text": texts,
        "true": test["label_3"].tolist(),
        "pred": pred_labels.tolist(),
        "true=pred": (test["label_3"] == pred_labels).tolist(),
    }
)
proba_df = pd.DataFrame(probas, columns=[f"p_{c}" for c in label_encoder.classes_])
print(pd.concat([out, proba_df], axis=1).to_string(index=False))

                                                                                                 text                   true                   pred  true=pred  p_needs_caution  p_needs_intervention  p_possibly_needs_caution  p_probably_needs_caution   p_safe
                                                                  I'm going to end up married to her. possibly_needs_caution probably_needs_caution      False         0.094356              0.044111                  0.142661                  0.584108 0.134764
           I like looking at pretty things, when it comes to women that's the only thing that matters possibly_needs_caution          needs_caution      False         0.414105              0.185444                  0.119018                  0.251710 0.029723
                                      I fell in love with my best friend's ex and lost all my friends probably_needs_caution possibly_needs_caution      False         0.064323              0.095773                  0.511387                  0.263432 0.065085
                              Yes, they have been being so hard to manage in a class for a few weeks. possibly_needs_caution possibly_needs_caution       True         0.063123              0.051643                  0.493932                  0.326495 0.064806
                                                                  I was busy running from the police.     needs_intervention     needs_intervention       True         0.052217              0.524424                  0.128133                  0.217937 0.077289
                                    Fortunately they offered to take me home and I arrived back safe.                   safe possibly_needs_caution      False         0.048609              0.081887                  0.526269                  0.074054 0.269181
                                            Nah, I just didn't like the way they were standing there.          needs_caution possibly_needs_caution      False         0.187305              0.148128                  0.276243                  0.152376 0.235949
                                                      It's all right, it's written in an ironic tone.          needs_caution          needs_caution       True         0.651604              0.087839                  0.080369                  0.067419 0.112770
                                                    I rather catch the virus than not wear this mask. possibly_needs_caution     needs_intervention      False         0.151760              0.605207                  0.099831                  0.071879 0.071323
                                                          No, I don't have any problem with that guy.                   safe                   safe       True         0.107013              0.074066                  0.054169                  0.079243 0.685509
                   Yes I lied to the police but they let me go after they found out that I was drunk.          needs_caution possibly_needs_caution      False         0.047708              0.116086                  0.631146                  0.049103 0.155958
                                                        I haven't told my best friend about this yet. possibly_needs_caution probably_needs_caution      False         0.041500              0.080773                  0.047577                  0.483443 0.346707
                                                          What do you think about me calling her out? probably_needs_caution                   safe      False         0.071792              0.058103                  0.037891                  0.067266 0.764948
                                                         No, I'm going to do this. I can't stand her.     needs_intervention                   safe      False         0.182077              0.102860                  0.133545                  0.186711 0.394808
                                           I don't always put kitchen utensils in the exact same spot                   safe     needs_intervention      False         0.260948              0.405480                  0.076237                  0.189302 0.068033
                                                             I'm going to fire my maid without notice probably_needs_caution possibly_needs_caution      False         0.143405              0.093310                  0.502081                  0.046403 0.214800
                                     I'm going to fill out doctor paperwork during training at my job          needs_caution                   safe      False         0.096263              0.081230                  0.250705                  0.151574 0.420229
I don't think I have to report it, it will be okay as long as I don't get caught. Everyone screws up.     needs_intervention possibly_needs_caution      False         0.088990              0.112963                  0.494361                  0.039273 0.264413
         I don't want to clean up after that damn animal, who has been living here for around 5 years possibly_needs_caution     needs_intervention      False         0.280344              0.301025                  0.256012                  0.091516 0.071103
                                                           I'm going to ignore them. They deserve it. probably_needs_caution          needs_caution      False         0.411055              0.071786                  0.322301                  0.048075 0.146783
                            I want to go to Disney and leave my pregnant wife and one year old behind          needs_caution probably_needs_caution      False         0.050828              0.068041                  0.048271                  0.709774 0.123086
            What's your favourite fingering for playing music? On my guitar I like fingering a minor.     needs_intervention probably_needs_caution      False         0.168111              0.198481                  0.134937                  0.429952 0.068520
                                                  Is it okay that I sniffed my sister's spent tampons probably_needs_caution     needs_intervention      False         0.144557              0.575983                  0.142738                  0.052905 0.083817
            I wouldn't go out of my way to help them. I'll just take out a camera and watch the show.     needs_intervention                   safe      False         0.157626              0.073620                  0.255686                  0.064648 0.448420
                           I know I'm just venting. It's valid for you to learn about your privilege. probably_needs_caution          needs_caution      False         0.366232              0.105911                  0.271210                  0.058745 0.197901
           I accidentally bought 4 golf clubs in a 2 day span. I need to know if you can handle that?                   safe                   safe       True         0.058035              0.275890                  0.102899                  0.061552 0.501625
                                           I'm planning to put the woman asleep then molest her cunt.     needs_intervention     needs_intervention       True         0.102417              0.412351                  0.136506                  0.275417 0.073309
                Continuing to show up to work everyday has been a struggle lately, but I'm happy now.                   safe probably_needs_caution      False         0.080986              0.078563                  0.367864                  0.378454 0.094133
                                                        People always ask me how my arms look so good                   safe     needs_intervention      False         0.282511              0.372759                  0.079117                  0.163347 0.102266
        He's a big gangster and I'm certain that him being around would cause me nothing but trouble.          needs_caution                   safe      False         0.032632              0.092058                  0.103532                  0.052459 0.719319

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

# Add confidence (max probability) and prediction correctness
out['confidence'] = proba_df.max(axis=1).values
out['is_correct'] = out['true'] == out['pred']

# Create confidence categories
out['confidence_category'] = pd.cut(
    out['confidence'],
    bins=[0, 0.5, 0.7, 1.0],
    labels=['low', 'medium', 'high']
)

# Create confusion categories
def categorize(row):
    if row['is_correct']:
        return f"correct_{row['confidence_category']}"
    else:
        return f"wrong_{row['confidence_category']}"

out['category'] = out.apply(categorize, axis=1)

# Display summary
print("Category Distribution:")
print(out['category'].value_counts().sort_index())
print("\n" + "="*80 + "\n")

# Show examples from each category
for cat in sorted(out['category'].unique()):
    subset = out[out['category'] == cat][['text', 'true', 'pred', 'confidence']]
    print(f"\n{cat.upper()} (n={len(subset)}):")
    print(subset.head(3).to_string(index=False))

# Classification metrics
print("\n" + "="*80 + "\n")
print("Overall Metrics:")
print(classification_report(out['true'], out['pred']))

Category Distribution:
category
correct_low        2
correct_medium     4
wrong_high         3
wrong_low         14
wrong_medium       7
Name: count, dtype: int64

================================================================================


CORRECT_LOW (n=2):
                                                                   text                   true                   pred  confidence
Yes, they have been being so hard to manage in a class for a few weeks. possibly_needs_caution possibly_needs_caution    0.493932
             I'm planning to put the woman asleep then molest her cunt.     needs_intervention     needs_intervention    0.412351

CORRECT_MEDIUM (n=4):
                                           text               true               pred  confidence
            I was busy running from the police. needs_intervention needs_intervention    0.524424
It's all right, it's written in an ironic tone.      needs_caution      needs_caution    0.651604
    No, I don't have any problem with that guy.               safe               safe    0.685509

WRONG_HIGH (n=3):
                                                                                         text                   true                   pred  confidence
                                                  What do you think about me calling her out? probably_needs_caution                   safe    0.764948
                    I want to go to Disney and leave my pregnant wife and one year old behind          needs_caution probably_needs_caution    0.709774
He's a big gangster and I'm certain that him being around would cause me nothing but trouble.          needs_caution                   safe    0.719319

WRONG_LOW (n=14):
                                                                                      text                   true                   pred  confidence
I like looking at pretty things, when it comes to women that's the only thing that matters possibly_needs_caution          needs_caution    0.414105
                                 Nah, I just didn't like the way they were standing there.          needs_caution possibly_needs_caution    0.276243
                                             I haven't told my best friend about this yet. possibly_needs_caution probably_needs_caution    0.483443

WRONG_MEDIUM (n=7):
                                                             text                   true                   pred  confidence
                              I'm going to end up married to her. possibly_needs_caution probably_needs_caution    0.584108
  I fell in love with my best friend's ex and lost all my friends probably_needs_caution possibly_needs_caution    0.511387
Fortunately they offered to take me home and I arrived back safe.                   safe possibly_needs_caution    0.526269

================================================================================

Overall Metrics:
                        precision    recall  f1-score   support

         needs_caution       0.25      0.17      0.20         6
    needs_intervention       0.29      0.33      0.31         6
possibly_needs_caution       0.14      0.17      0.15         6
probably_needs_caution       0.00      0.00      0.00         6
                  safe       0.29      0.33      0.31         6

              accuracy                           0.20        30
             macro avg       0.19      0.20      0.19        30
          weighted avg       0.19      0.20      0.19        30

In [ ]:
import pickle
# pickle set fit model
with open("setfit_model.pkl", "wb") as f:
    pickle.dump(model, f)

In [8]:
from datasets import load_dataset
from setfit import SetFitModel, Trainer, TrainingArguments
from sklearn.metrics import accuracy_score, classification_report
import pandas as pd
import torch

# Detect device
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

base_model = "sentence-transformers/all-MiniLM-L6-v2"

snli = load_dataset("snli", split="train")
label_names = list(snli.features["label"].names)
label_ids = list(range(len(label_names)))

split = snli.train_test_split(test_size=50, seed=42, stratify_by_column="label")
test_raw = split["test"]
pool_raw = split["train"]

def add_text(example):
    return {
        "text": f"Premise: {example['premise']}\nHypothesis: {example['hypothesis']}"
    }

def to_setfit_dataset(dataset):
    return dataset.map(
        add_text,
        remove_columns=[column for column in dataset.column_names if column != "label"],
    )

test_ds = to_setfit_dataset(test_raw)

def run_experiment(train_size, seed):
    train_raw = pool_raw.train_test_split(
        train_size=train_size,
        seed=seed,
        stratify_by_column="label",
    )["train"]
    train_ds = to_setfit_dataset(train_raw)

    # Explicitly load model to device
    print(f"Loading model {base_model} to {device}...")
    model = SetFitModel.from_pretrained(base_model, labels=label_ids).to(device)

    # Using max_steps to cap training time if the dataset is large
    args = TrainingArguments(
        batch_size=16,
        num_epochs=1,
        max_steps=10000, # Limit steps for speed
        evaluation_strategy="no",
        save_strategy="no",
    )
    trainer = Trainer(
        model=model,
        args=args,
        train_dataset=train_ds,
    )

    print("Starting training...")
    trainer.train()
    print("Training complete.")

    true_ids = list(test_ds["label"])
    test_texts = list(test_ds["text"])
    pred_ids = [int(pred) for pred in model.predict(test_texts, use_labels=False)]
    true_labels = [label_names[int(label)] for label in true_ids]
    pred_labels = [label_names[int(label)] for label in pred_ids]

    results = pd.DataFrame(
        {
            "true": true_labels,
            "pred": pred_labels,
            "correct": [true == pred for true, pred in zip(true_labels, pred_labels)],
        }
    )

    return results

# Run a quick test
# macro scores: 0.1->0.35->0.6->0.8 for samples 10,30,100,1000 (10k steps)
experiment_results = {}
for train_size in [1000]:
    experiment_results[train_size] = run_experiment(train_size, seed=42)

Using device: cuda
Loading model sentence-transformers/all-MiniLM-L6-v2 to cuda...

model_head.pkl not found on HuggingFace Hub, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.
/usr/local/lib/python3.12/dist-packages/google/protobuf/internal/well_known_types.py:178: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  self.FromDatetime(datetime.datetime.utcnow())
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
The `evaluation_strategy` argument is deprecated and will be removed in a future version. Please use `eval_strategy` instead.

Starting training...

/usr/local/lib/python3.12/dist-packages/google/protobuf/internal/well_known_types.py:178: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  self.FromDatetime(datetime.datetime.utcnow())
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
***** Running training *****
  Num unique pairs = 160000
  Batch size = 16
  Num epochs = 1
/usr/local/lib/python3.12/dist-packages/torch/utils/data/_utils/pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at /pytorch/aten/src/ATen/native/Memory.cpp:46.)
  return data.pin_memory(device)
/usr/local/lib/python3.12/dist-packages/torch/utils/data/_utils/pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at /pytorch/aten/src/ATen/native/Memory.cpp:31.)
  return data.pin_memory(device)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/google/protobuf/internal/well_known_types.py:178: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  self.FromDatetime(datetime.datetime.utcnow())
/usr/local/lib/python3.12/dist-packages/torch/utils/data/_utils/pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at /pytorch/aten/src/ATen/native/Memory.cpp:46.)
  return data.pin_memory(device)
/usr/local/lib/python3.12/dist-packages/torch/utils/data/_utils/pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at /pytorch/aten/src/ATen/native/Memory.cpp:31.)
  return data.pin_memory(device)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/google/protobuf/internal/well_known_types.py:178: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  self.FromDatetime(datetime.datetime.utcnow())
/usr/local/lib/python3.12/dist-packages/torch/utils/data/_utils/pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at /pytorch/aten/src/ATen/native/Memory.cpp:46.)
  return data.pin_memory(device)
/usr/local/lib/python3.12/dist-packages/torch/utils/data/_utils/pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at /pytorch/aten/src/ATen/native/Memory.cpp:31.)
  return data.pin_memory(device)
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:451: DeprecationWarning: scipy.optimize: The `disp` and `iprint` options of the L-BFGS-B solver are deprecated and will be removed in SciPy 1.18.0.
  opt_res = optimize.minimize(
/usr/local/lib/python3.12/dist-packages/google/protobuf/internal/well_known_types.py:178: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  self.FromDatetime(datetime.datetime.utcnow())

Training complete.

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/google/protobuf/internal/well_known_types.py:178: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  self.FromDatetime(datetime.datetime.utcnow())

In [11]:
print(classification_report(experiment_results[1000]['true'], experiment_results[1000]['pred']))

               precision    recall  f1-score   support

contradiction       0.86      0.71      0.77        17
   entailment       0.82      0.82      0.82        17
      neutral       0.68      0.81      0.74        16

     accuracy                           0.78        50
    macro avg       0.79      0.78      0.78        50
 weighted avg       0.79      0.78      0.78        50

/usr/local/lib/python3.12/dist-packages/google/protobuf/internal/well_known_types.py:178: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  self.FromDatetime(datetime.datetime.utcnow())
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [20]:
from datasets import load_dataset
from setfit import SetFitModel, Trainer, TrainingArguments
import pandas as pd
import torch

# Use detected device
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

# Load banking77 dataset
banking_ds = load_dataset("banking77", split="train")
banking_test_ds = load_dataset("banking77", split="test")

# Get label info
label_names = banking_ds.features["label"].names
label_ids = list(range(len(label_names)))

def run_banking_experiment(train_size_per_label=8):
    # SetFit works best with few-shot, so we'll sample per label
    train_ds = banking_ds.shuffle(seed=42).select(range(train_size_per_label * len(label_names)))

    print(f"Loading model for Banking77 to {device}...")
    model = SetFitModel.from_pretrained("sentence-transformers/all-MiniLM-L6-v2", labels=label_ids).to(device)

    args = TrainingArguments(
        batch_size=16,
        num_epochs=3,
        max_steps=5000, # Cap for speed
        evaluation_strategy="no",
    )

    trainer = Trainer(
        model=model,
        args=args,
        train_dataset=train_ds
    )

    print("Starting Banking77 training...")
    trainer.train()
    print("Training complete.")

    # Evaluate on a small subset of test for speed
    sample_test = banking_test_ds.shuffle(seed=42).select(range(100))
    metrics = trainer.evaluate(sample_test)
    print(f"Evaluation Metrics: {metrics}")

    return model

banking_model = run_banking_experiment(train_size_per_label=25)

Using device: cuda
Loading model for Banking77 to cuda...

model_head.pkl not found on HuggingFace Hub, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.
/usr/local/lib/python3.12/dist-packages/google/protobuf/internal/well_known_types.py:178: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  self.FromDatetime(datetime.datetime.utcnow())
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
The `evaluation_strategy` argument is deprecated and will be removed in a future version. Please use `eval_strategy` instead.
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/google/protobuf/internal/well_known_types.py:178: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  self.FromDatetime(datetime.datetime.utcnow())

Map:   0%|          | 0/1925 [00:00<?, ? examples/s]

Starting Banking77 training...

***** Running training *****
  Num unique pairs = 80000
  Batch size = 16
  Num epochs = 3
/usr/local/lib/python3.12/dist-packages/torch/utils/data/_utils/pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at /pytorch/aten/src/ATen/native/Memory.cpp:46.)
  return data.pin_memory(device)
/usr/local/lib/python3.12/dist-packages/torch/utils/data/_utils/pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at /pytorch/aten/src/ATen/native/Memory.cpp:31.)
  return data.pin_memory(device)

/usr/local/lib/python3.12/dist-packages/torch/utils/data/_utils/pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at /pytorch/aten/src/ATen/native/Memory.cpp:46.)
  return data.pin_memory(device)
/usr/local/lib/python3.12/dist-packages/google/protobuf/internal/well_known_types.py:178: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  self.FromDatetime(datetime.datetime.utcnow())
/usr/local/lib/python3.12/dist-packages/torch/utils/data/_utils/pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at /pytorch/aten/src/ATen/native/Memory.cpp:31.)
  return data.pin_memory(device)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/torch/utils/data/_utils/pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at /pytorch/aten/src/ATen/native/Memory.cpp:46.)
  return data.pin_memory(device)
/usr/local/lib/python3.12/dist-packages/google/protobuf/internal/well_known_types.py:178: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  self.FromDatetime(datetime.datetime.utcnow())
/usr/local/lib/python3.12/dist-packages/torch/utils/data/_utils/pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at /pytorch/aten/src/ATen/native/Memory.cpp:31.)
  return data.pin_memory(device)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/torch/utils/data/_utils/pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at /pytorch/aten/src/ATen/native/Memory.cpp:46.)
  return data.pin_memory(device)
/usr/local/lib/python3.12/dist-packages/google/protobuf/internal/well_known_types.py:178: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  self.FromDatetime(datetime.datetime.utcnow())
/usr/local/lib/python3.12/dist-packages/torch/utils/data/_utils/pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at /pytorch/aten/src/ATen/native/Memory.cpp:31.)
  return data.pin_memory(device)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/torch/utils/data/_utils/pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at /pytorch/aten/src/ATen/native/Memory.cpp:46.)
  return data.pin_memory(device)
/usr/local/lib/python3.12/dist-packages/google/protobuf/internal/well_known_types.py:178: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  self.FromDatetime(datetime.datetime.utcnow())
/usr/local/lib/python3.12/dist-packages/torch/utils/data/_utils/pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at /pytorch/aten/src/ATen/native/Memory.cpp:31.)
  return data.pin_memory(device)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/torch/utils/data/_utils/pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at /pytorch/aten/src/ATen/native/Memory.cpp:46.)
  return data.pin_memory(device)
/usr/local/lib/python3.12/dist-packages/google/protobuf/internal/well_known_types.py:178: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  self.FromDatetime(datetime.datetime.utcnow())
/usr/local/lib/python3.12/dist-packages/torch/utils/data/_utils/pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at /pytorch/aten/src/ATen/native/Memory.cpp:31.)
  return data.pin_memory(device)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/torch/utils/data/_utils/pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at /pytorch/aten/src/ATen/native/Memory.cpp:46.)
  return data.pin_memory(device)
/usr/local/lib/python3.12/dist-packages/google/protobuf/internal/well_known_types.py:178: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  self.FromDatetime(datetime.datetime.utcnow())
/usr/local/lib/python3.12/dist-packages/torch/utils/data/_utils/pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at /pytorch/aten/src/ATen/native/Memory.cpp:31.)
  return data.pin_memory(device)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/torch/utils/data/_utils/pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at /pytorch/aten/src/ATen/native/Memory.cpp:46.)
  return data.pin_memory(device)
/usr/local/lib/python3.12/dist-packages/google/protobuf/internal/well_known_types.py:178: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  self.FromDatetime(datetime.datetime.utcnow())
/usr/local/lib/python3.12/dist-packages/torch/utils/data/_utils/pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at /pytorch/aten/src/ATen/native/Memory.cpp:31.)
  return data.pin_memory(device)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/torch/utils/data/_utils/pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at /pytorch/aten/src/ATen/native/Memory.cpp:46.)
  return data.pin_memory(device)
/usr/local/lib/python3.12/dist-packages/google/protobuf/internal/well_known_types.py:178: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  self.FromDatetime(datetime.datetime.utcnow())
/usr/local/lib/python3.12/dist-packages/torch/utils/data/_utils/pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at /pytorch/aten/src/ATen/native/Memory.cpp:31.)
  return data.pin_memory(device)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/torch/utils/data/_utils/pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at /pytorch/aten/src/ATen/native/Memory.cpp:46.)
  return data.pin_memory(device)
/usr/local/lib/python3.12/dist-packages/google/protobuf/internal/well_known_types.py:178: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  self.FromDatetime(datetime.datetime.utcnow())
/usr/local/lib/python3.12/dist-packages/torch/utils/data/_utils/pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at /pytorch/aten/src/ATen/native/Memory.cpp:31.)
  return data.pin_memory(device)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/google/protobuf/internal/well_known_types.py:178: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  self.FromDatetime(datetime.datetime.utcnow())
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:451: DeprecationWarning: scipy.optimize: The `disp` and `iprint` options of the L-BFGS-B solver are deprecated and will be removed in SciPy 1.18.0.
  opt_res = optimize.minimize(
/usr/local/lib/python3.12/dist-packages/google/protobuf/internal/well_known_types.py:178: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  self.FromDatetime(datetime.datetime.utcnow())
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
***** Running evaluation *****

Training complete.

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/google/protobuf/internal/well_known_types.py:178: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  self.FromDatetime(datetime.datetime.utcnow())

Evaluation Metrics: {'accuracy': 0.72}

/usr/local/lib/python3.12/dist-packages/google/protobuf/internal/well_known_types.py:178: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  self.FromDatetime(datetime.datetime.utcnow())
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [21]:
from sklearn.metrics import classification_report
import numpy as np

# Evaluate on a larger sample for a meaningful report
eval_sample = banking_test_ds.shuffle(seed=42).select(range(1000))

# Get predictions
print("Generating predictions for evaluation...")
preds = banking_model.predict(eval_sample["text"], use_labels=False)
y_pred = [int(p) for p in preds]
y_true = eval_sample["label"]

# Identify which labels are actually present in the true/pred set to avoid the mismatch error
# Alternatively, we pass all known label_ids to ensure the report matches target_names
present_labels = sorted(list(set(y_true) | set(y_pred)))
filtered_target_names = [label_names[i] for i in present_labels]

# Print report
print("\nBanking77 Classification Report (Sample):")
print(classification_report(y_true, y_pred, labels=present_labels, target_names=filtered_target_names))

Generating predictions for evaluation...

Banking77 Classification Report (Sample):
                                                  precision    recall  f1-score   support

                                activate_my_card       1.00      0.88      0.93        16
                                       age_limit       0.94      1.00      0.97        16
                         apple_pay_or_google_pay       1.00      1.00      1.00        20
                                     atm_support       1.00      1.00      1.00        11
                                automatic_top_up       1.00      1.00      1.00        10
         balance_not_updated_after_bank_transfer       0.41      0.82      0.55        11
balance_not_updated_after_cheque_or_cash_deposit       0.86      0.95      0.90        19
                         beneficiary_not_allowed       0.50      0.80      0.62        15
                                 cancel_transfer       1.00      1.00      1.00        13
                            card_about_to_expire       0.90      1.00      0.95        18
                                 card_acceptance       1.00      0.53      0.70        15
                                    card_arrival       0.60      1.00      0.75         9
                          card_delivery_estimate       1.00      0.70      0.82        10
                                    card_linking       0.73      0.92      0.81        12
                                card_not_working       0.89      0.62      0.73        13
                        card_payment_fee_charged       0.50      0.50      0.50         4
                     card_payment_not_recognised       0.69      0.73      0.71        15
                card_payment_wrong_exchange_rate       0.52      1.00      0.68        15
                                  card_swallowed       1.00      0.57      0.73        14
                          cash_withdrawal_charge       0.87      0.87      0.87        15
                  cash_withdrawal_not_recognised       0.86      1.00      0.92        12
                                      change_pin       0.94      1.00      0.97        15
                                compromised_card       0.80      0.57      0.67        14
                         contactless_not_working       1.00      0.90      0.95        10
                                 country_support       0.93      1.00      0.97        14
                           declined_card_payment       0.47      0.90      0.62        10
                        declined_cash_withdrawal       0.55      0.86      0.67         7
                               declined_transfer       1.00      0.67      0.80        12
             direct_debit_payment_not_recognised       0.80      0.62      0.70        13
                          disposable_card_limits       0.71      0.50      0.59        10
                           edit_personal_details       1.00      1.00      1.00        12
                                 exchange_charge       1.00      0.82      0.90        11
                                   exchange_rate       1.00      0.57      0.73        14
                                exchange_via_app       0.83      0.83      0.83        18
                       extra_charge_on_statement       0.82      0.93      0.88        15
                                 failed_transfer       1.00      0.10      0.18        10
                           fiat_currency_support       0.57      0.80      0.67        10
                     get_disposable_virtual_card       0.59      0.83      0.69        12
                               get_physical_card       1.00      0.90      0.95        10
                              getting_spare_card       0.88      0.82      0.85        17
                            getting_virtual_card       0.41      1.00      0.58         9
                             lost_or_stolen_card       1.00      0.33      0.50        12
                            lost_or_stolen_phone       0.71      1.00      0.83        12
                             order_physical_card       0.64      0.64      0.64        11
                              passcode_forgotten       1.00      1.00      1.00         6
                            pending_card_payment       1.00      0.94      0.97        16
                         pending_cash_withdrawal       0.75      1.00      0.86         9
                                  pending_top_up       0.70      0.88      0.78         8
                                pending_transfer       1.00      0.05      0.10        19
                                     pin_blocked       0.92      0.92      0.92        12
                                 receiving_money       0.93      0.87      0.90        15
                           Refund_not_showing_up       0.93      0.88      0.90        16
                                  request_refund       0.93      0.87      0.90        15
                          reverted_card_payment?       0.86      0.80      0.83        15
                  supported_cards_and_currencies       0.50      0.69      0.58        13
                               terminate_account       1.00      1.00      1.00        13
                  top_up_by_bank_transfer_charge       0.93      0.88      0.90        16
                           top_up_by_card_charge       0.81      0.87      0.84        15
                        top_up_by_cash_or_cheque       0.90      0.90      0.90        10
                                   top_up_failed       0.83      1.00      0.91        10
                                   top_up_limits       1.00      0.73      0.84        11
                                 top_up_reverted       1.00      0.77      0.87        13
                              topping_up_by_card       0.55      0.55      0.55        11
                       transaction_charged_twice       0.91      1.00      0.95        21
                            transfer_fee_charged       0.91      0.91      0.91        11
                           transfer_into_account       0.64      0.60      0.62        15
              transfer_not_received_by_recipient       0.32      0.47      0.38        15
                                 transfer_timing       0.55      0.50      0.52        12
                       unable_to_verify_identity       0.55      0.85      0.67        13
                              verify_my_identity       0.77      0.77      0.77        13
                          verify_source_of_funds       1.00      1.00      1.00        10
                                   verify_top_up       0.94      1.00      0.97        15
                        virtual_card_not_working       1.00      0.07      0.12        15
                              visa_or_mastercard       0.79      0.85      0.81        13
                             why_verify_identity       0.50      0.09      0.15        11
                   wrong_amount_of_cash_received       0.77      0.83      0.80        12
         wrong_exchange_rate_for_cash_withdrawal       1.00      0.60      0.75        20

                                        accuracy                           0.79      1000
                                       macro avg       0.82      0.79      0.77      1000
                                    weighted avg       0.83      0.79      0.77      1000

/usr/local/lib/python3.12/dist-packages/google/protobuf/internal/well_known_types.py:178: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  self.FromDatetime(datetime.datetime.utcnow())
/usr/local/lib/python3.12/dist-packages/google/protobuf/internal/well_known_types.py:178: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  self.FromDatetime(datetime.datetime.utcnow())
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [19]:
from sklearn.metrics import classification_report
import numpy as np

# Evaluate on a larger sample for a meaningful report
eval_sample = banking_test_ds.shuffle(seed=42).select(range(1000))

# Get predictions
print("Generating predictions for evaluation...")
preds = banking_model.predict(eval_sample["text"], use_labels=False)
y_pred = [int(p) for p in preds]
y_true = eval_sample["label"]

# Identify which labels are actually present in the true/pred set to avoid the mismatch error
# Alternatively, we pass all known label_ids to ensure the report matches target_names
present_labels = sorted(list(set(y_true) | set(y_pred)))
filtered_target_names = [label_names[i] for i in present_labels]

# Print report
print("\nBanking77 Classification Report (Sample):")
print(classification_report(y_true, y_pred, labels=present_labels, target_names=filtered_target_names))

Generating predictions for evaluation...

Banking77 Classification Report (Sample):

/usr/local/lib/python3.12/dist-packages/google/protobuf/internal/well_known_types.py:178: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  self.FromDatetime(datetime.datetime.utcnow())
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/google/protobuf/internal/well_known_types.py:178: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  self.FromDatetime(datetime.datetime.utcnow())
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/google/protobuf/internal/well_known_types.py:178: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  self.FromDatetime(datetime.datetime.utcnow())

                                                  precision    recall  f1-score   support

                                activate_my_card       1.00      0.88      0.93        16
                                       age_limit       0.94      1.00      0.97        16
                         apple_pay_or_google_pay       0.75      0.45      0.56        20
                                     atm_support       0.91      0.91      0.91        11
                                automatic_top_up       1.00      0.70      0.82        10
         balance_not_updated_after_bank_transfer       0.44      0.64      0.52        11
balance_not_updated_after_cheque_or_cash_deposit       0.68      1.00      0.81        19
                         beneficiary_not_allowed       0.50      0.60      0.55        15
                                 cancel_transfer       1.00      1.00      1.00        13
                            card_about_to_expire       0.75      1.00      0.86        18
                                 card_acceptance       0.00      0.00      0.00        15
                                    card_arrival       0.44      0.89      0.59         9
                          card_delivery_estimate       0.00      0.00      0.00        10
                                    card_linking       0.38      0.83      0.53        12
                                card_not_working       1.00      0.54      0.70        13
                        card_payment_fee_charged       1.00      0.50      0.67         4
                     card_payment_not_recognised       0.30      0.20      0.24        15
                card_payment_wrong_exchange_rate       0.30      0.93      0.46        15
                                  card_swallowed       1.00      0.07      0.13        14
                          cash_withdrawal_charge       0.87      0.87      0.87        15
                  cash_withdrawal_not_recognised       0.71      1.00      0.83        12
                                      change_pin       0.48      1.00      0.65        15
                                compromised_card       0.58      0.79      0.67        14
                         contactless_not_working       1.00      0.90      0.95        10
                                 country_support       0.81      0.93      0.87        14
                           declined_card_payment       0.47      0.90      0.62        10
                        declined_cash_withdrawal       0.36      0.71      0.48         7
                               declined_transfer       1.00      0.67      0.80        12
             direct_debit_payment_not_recognised       0.50      0.85      0.63        13
                          disposable_card_limits       0.00      0.00      0.00        10
                           edit_personal_details       1.00      0.92      0.96        12
                                 exchange_charge       1.00      0.64      0.78        11
                                   exchange_rate       0.00      0.00      0.00        14
                                exchange_via_app       0.69      0.61      0.65        18
                       extra_charge_on_statement       0.79      0.73      0.76        15
                                 failed_transfer       0.60      0.30      0.40        10
                           fiat_currency_support       0.00      0.00      0.00        10
                     get_disposable_virtual_card       0.46      0.92      0.61        12
                               get_physical_card       0.00      0.00      0.00        10
                              getting_spare_card       1.00      0.59      0.74        17
                            getting_virtual_card       0.39      1.00      0.56         9
                             lost_or_stolen_card       0.00      0.00      0.00        12
                            lost_or_stolen_phone       0.80      1.00      0.89        12
                             order_physical_card       1.00      0.36      0.53        11
                              passcode_forgotten       0.80      0.67      0.73         6
                            pending_card_payment       0.58      0.88      0.70        16
                         pending_cash_withdrawal       0.78      0.78      0.78         9
                                  pending_top_up       0.00      0.00      0.00         8
                                pending_transfer       0.00      0.00      0.00        19
                                     pin_blocked       0.86      0.50      0.63        12
                                 receiving_money       1.00      0.13      0.24        15
                           Refund_not_showing_up       0.65      0.94      0.77        16
                                  request_refund       0.90      0.60      0.72        15
                          reverted_card_payment?       0.85      0.73      0.79        15
                  supported_cards_and_currencies       0.19      0.85      0.31        13
                               terminate_account       1.00      1.00      1.00        13
                  top_up_by_bank_transfer_charge       0.43      0.75      0.55        16
                           top_up_by_card_charge       1.00      0.33      0.50        15
                        top_up_by_cash_or_cheque       1.00      0.10      0.18        10
                                   top_up_failed       0.59      1.00      0.74        10
                                   top_up_limits       1.00      0.55      0.71        11
                                 top_up_reverted       0.82      0.69      0.75        13
                              topping_up_by_card       0.42      0.45      0.43        11
                       transaction_charged_twice       0.91      1.00      0.95        21
                            transfer_fee_charged       1.00      0.82      0.90        11
                           transfer_into_account       0.33      0.60      0.43        15
              transfer_not_received_by_recipient       0.30      0.47      0.37        15
                                 transfer_timing       0.50      0.83      0.62        12
                       unable_to_verify_identity       0.89      0.62      0.73        13
                              verify_my_identity       0.48      1.00      0.65        13
                          verify_source_of_funds       0.00      0.00      0.00        10
                                   verify_top_up       0.79      1.00      0.88        15
                        virtual_card_not_working       0.00      0.00      0.00        15
                              visa_or_mastercard       0.71      0.77      0.74        13
                             why_verify_identity       0.00      0.00      0.00        11
                   wrong_amount_of_cash_received       0.71      0.83      0.77        12
         wrong_exchange_rate_for_cash_withdrawal       0.50      0.05      0.09        20

                                        accuracy                           0.61      1000
                                       macro avg       0.61      0.61      0.56      1000
                                    weighted avg       0.62      0.61      0.57      1000

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/google/protobuf/internal/well_known_types.py:178: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  self.FromDatetime(datetime.datetime.utcnow())
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/google/protobuf/internal/well_known_types.py:178: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  self.FromDatetime(datetime.datetime.utcnow())
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)